services:
  playground:
    container_name: playground
    build: ./compose
    restart: always
    env_file:
      - .env
    volumes:
      - "./src:/var/www/html"
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=web"
      - "traefik.http.routers.playground.rule=Host(\"${DOMAIN}\")"
      - "traefik.http.routers.playground.entrypoints=websecure"
      - "traefik.http.routers.playground.tls.certresolver=myresolver"
    networks:
      web:
      mariadb:
networks:
  web:
    name: web
    external: true
  mariadb:
    name: mariadb
    external: true
